module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: 2021,
    sourceType: "module",
  },
  plugins: ["react", "@typescript-eslint", "prettier"],
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
  ],
  rules: {
    'no-alert': 'error',
    '@typescript-eslint/no-explicit-any': 'warn',
    'prettier/prettier': 'error',
    'no-console': [2],
    'no-with': 2,
    'max-len': [1, 180, 4],
    'no-debugger': 2,
    'no-use-before-define': [2, { functions: false }],
    'no-multiple-empty-lines': [2, { max: 1, maxEOF: 0, maxBOF: 0 }],
    'no-prototype-builtins': 0,
    'no-extra-semi': 1,
    'no-unreachable': 1,
    'no-case-declarations': [1],
    'no-trailing-spaces': 2,
    'space-before-function-paren': 'off',
    'no-return-assign': [1],
    'guard-for-in': 2,
    'spaced-comment': [1, 'always'],
    'valid-typeof': 2,
    'react/no-unsafe': 2,
    'react/self-closing-comp': [1, { component: true, html: true }],
    'react/prop-types': [0],
    'react/display-name': 0,
    'react/no-children-prop': 2,
    'react/no-this-in-sfc': 2,
    'react/no-deprecated': 2,
    'react/no-direct-mutation-state': 1,
    'react/no-is-mounted': 1,
    'react/boolean-prop-naming': 0,
    'react/react-in-jsx-scope': 0,
    'react/require-render-return': 2,
    'react/jsx-closing-tag-location': 1,
    'react/jsx-equals-spacing': 1,
    'react/jsx-wrap-multilines': 1,
    'react/jsx-no-comment-textnodes': 1,
    'react/jsx-no-undef': 2,
    'react/jsx-no-useless-fragment': 1,
    'react/jsx-pascal-case': 2,
    'react/jsx-tag-spacing': 1,
    'react/jsx-uses-react': 2,
    'react/jsx-no-duplicate-props': 1,
    'react/jsx-filename-extension': 0,
    'import/extensions': 0,
    'import/no-unresolved': 0
  },
  settings: {
    react: {
      version: "detect",
    },
  },
};
